### ISSUE TITLE
Configs moved to a subdir, please adapt square 1

### ISSUE THREAD

**Issue by asamalik** [minimization/feedback-pipeline-config#19]
Hi @tdawson, I've moved all the configs to a subdirectory so the repository here on GitHub shows the README better. I know you're pushing the ELN Buildroot workload automatically to this repo. Can you please tweak your script to push it to the `configs` directory?

**Comment by tdawson** [comment]
Scripts that interact with the configs have been updated for the new place.
job that does this work has been updated and restarted.
Done.

**Comment by asamalik** [comment]
Thanks!
